# Generated by Django 4.0.1 on 2022-02-16 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourHood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood Title')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Neighbourhood Location')),
                ('neighbourhood_logo', models.ImageField(default='', upload_to='Neighbourhood_Pics', verbose_name='NeighbourHood Logo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('neighbourhood_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Neighbourhood Admin')),
            ],
            options={
                'verbose_name_plural': 'NeighbourHoods',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=254, verbose_name='Bio')),
                ('profile_picture', models.ImageField(default='', upload_to='Prof_Pics', verbose_name='Profile Pic')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Is Confirmed?')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('neighbourhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Neighbourhood.neighbourhood', verbose_name='NeighbourHood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='Post Title')),
                ('description', models.TextField(null=True, verbose_name='Post Description')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighbourhood.profile', verbose_name='Post Author')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighbourhood.neighbourhood', verbose_name='Rlated NeighbourHood')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('email', models.CharField(blank=True, max_length=150, null=True, verbose_name='Business Email Address')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date Updated')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighbourhood.neighbourhood', verbose_name='NeighbourHood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Neighbourhood.profile', verbose_name='Business Owner')),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
    ]
