# Generated by Django 4.0.1 on 2022-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Neighbourhood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='county',
            field=models.CharField(blank=True, choices=[('', 'Choose'), ('Baringo', 'Baringo'), ('Bomet', 'Bomet'), ('Bungoma ', 'Bungoma '), ('Busia', 'Busia'), ('Elgeyo Marakwet', 'Elgeyo Marakwet'), ('Embu', 'Embu'), ('Garissa', 'Garissa'), ('Homa Bay', 'Homa Bay'), ('Isiolo', 'Isiolo'), ('Kajiado', 'Kajiado'), ('Kakamega', 'Kakamega'), ('Kericho', 'Kericho'), ('Kiambu', 'Kiambu'), ('Kilifi', 'Kilifi'), ('Kirinyaga', 'Kirinyaga'), ('Kisii', 'Kisii'), ('Kisumu', 'Kisumu'), ('Kitui', 'Kitui'), ('Kwale', 'Kwale'), ('Laikipia', 'Laikipia'), ('Lamu', 'Lamu'), ('Machakos', 'Machakos'), ('Makueni', 'Makueni'), ('Mandera', 'Mandera'), ('Meru', 'Meru'), ('Migori', 'Migori'), ('Marsabit', 'Marsabit'), ('Mombasa', 'Mombasa'), ('Muranga', 'Muranga'), ('Nairobi', 'Nairobi'), ('Nakuru', 'Nakuru'), ('Nandi', 'Nandi'), ('Narok', 'Narok'), ('Nyamira', 'Nyamira'), ('Nyandarua', 'Nyandarua'), ('Nyeri', 'Nyeri'), ('Samburu', 'Samburu'), ('Siaya', 'Siaya'), ('Taita Taveta', 'Taita Taveta'), ('Tana River', 'Tana River'), ('Tharaka Nithi', 'Tharaka Nithi'), ('Trans Nzoia', 'Trans Nzoia'), ('Turkana', 'Turkana'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'Vihiga'), ('Wajir', 'Wajir'), ('West Pokot', 'West Pokot')], max_length=150, null=True, verbose_name='Neighbourhood County'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_logo',
            field=models.ImageField(upload_to='Neighbourhood-Logo', verbose_name='NeighbourHood Logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='Profile-Pics', verbose_name='Profile Picture'),
        ),
    ]
